# Use Ubuntu 22.04 for the base image
FROM ubuntu:22.04

# Prevent interactive prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Install dependencies for Godot and .NET
RUN apt-get update && apt-get install -y \
    ca-certificates \
    wget \
    unzip \
    libfontconfig1 \
    libdbus-1-3 \
    libxcursor1 \
    libxinerama1 \
    libxrandr2 \
    libxi6 \
    libgl1-mesa-glx \
    libglu1-mesa \
    libxrender1 \
    libpulse0 \
    libasound2 \
    libnss3 \
    libnspr4 \
    libgconf-2-4 \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libcups2 \
    libdrm2 \
    libgbm1 \
    libxcomposite1 \
    libxdamage1 \
    libxkbcommon0 \
    libpango-1.0-0 \
    libcairo2 \
    libasound2 \
    dotnet-sdk-8.0 \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy the headless server export (to be generated by build script)
# Expecting: 
#   OkieRummyServer.x86_64
#   OkieRummyServer.pck
COPY ./godot/exports/server/ /app/

# Make the binary executable
RUN chmod +x /app/OkieRummyServer.x86_64

# Expose the game server port (UDP)
EXPOSE 8080/udp

# Run the server
CMD ["./OkieRummyServer.x86_64", "--headless"]
